apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: traceofhumanity/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'auth/**/*.ts'
            dest: /.
    - image: traceofhumanity/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'client/**/*.js'
            dest: /.
    - image: traceofhumanity/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'tickets/**/*.ts'
            dest: /.
    - image: traceofhumanity/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'orders/**/*.ts'
            dest: /.
